--- 
ReportDefinitions:
- reportName: new_report_test
  summary: New Report Test
  version: 1.0.0
  moduleName: rainmaker-pt
  sourceColumns:
  - name: receipttype
    label: reports.pt.receiptNo
    type: string
    source: pt
    total: false
  - name: propertyid
    label: reports.pt.receiptDate
    type: string
    source: pt
    total: false
  - name: assessmentnumber
    label: reports.pt.g8issuedate
    type: string
    source: pt
    total: false
  - name: payeename
    label: reports.pt.g8receiptno
    type: string
    source: pt
    total: false
  - name: totalamount
    label: reports.pt.amount
    type: string
    source: pt
    total: true
  query: |
      -- Use CTE to force query plan, compute & use CTE later    
      SELECT 
        rh.tenantid AS tenantid, 
        rh.receipttype AS Type, 
        Substring(rh.consumercode, '(.*):') AS propertyid, 
        Substring(rh.consumercode, ':(.*)') AS assessmentnumber, 
        rh.payeename, 
        rh.totalamount AS AmountPaid 
        
      FROM egcl_receiptheader AS rh
      WHERE rh.tenantid LIKE $tenantid and rh.status != 'Cancelled'
  orderby: ORDER BY rh.receiptdate DESC
