---
ReportDefinitions:
- reportName: ReceiptRegister
  summary: Receipt Register
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: receiptnumber
    label: reports.tl.receiptNo
    type: string
    source: tl
    total: false
  - name: date
    label: reports.tl.receiptDate
    type: string
    source: tl
    total: false
  - name: calculatedamount
    label: reports.tl.amount
    type: string
    source: tl
    total: true
  - name: tltax
    label: reports.tl.tlTax
    type: string
    source: tl
    total: true
  - name: applicationnumber
    label: reports.tl.applicationNo
    type: string
    source: tl
    total: false
  - name: transactionid
    label: reports.tl.transactionNo
    type: string
    source: tl
    total: false
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND receiptdate >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND receiptdate <= $toDate
  query: SELECT id, receiptnumber, transactionid, consumercode AS applicationnumber, tenantid, adhocpenalty, adhocrebate, tltax, (tltax + adhocpenalty + adhocrebate) AS calculatedamount, totalamount, receiptdate, To_char(To_timestamp(receiptdate / 1000), 'DD/MM/YYYY') AS date FROM (SELECT receiptnumber, consumercode, totalamount, id, tenantid, receiptdate, transactionid FROM egcl_receiptheader WHERE businessdetails = 'TL') AS a LEFT OUTER JOIN (SELECT receiptheader, SUM(CASE WHEN description LIKE 'TL_ADHOC_PENALTY%' THEN cramount ELSE 0 END) as adhocpenalty, SUM(CASE WHEN description LIKE 'TL_ADHOC_REBATE%' THEN -dramount ELSE 0 END) as adhocrebate, SUM(CASE WHEN description LIKE 'TL_TAX%' THEN cramount ELSE 0 END) as tltax FROM egcl_receiptdetails group by receiptheader) AS b ON a.id = b.receiptheader WHERE tenantid LIKE $tenantid
  orderby: ORDER BY receiptdate DESC