SearchDefinitions:
 moduleName: rainmaker-pt-customsearch-punjab
 summary: Vasika number search for punjab
 version: 1.0.0
 definitions:
 - name: searchPropertyIDByVasikaNo
   query: 
    baseQuery: |
      select 
        array_to_json(array_agg(row_to_json(vasika_results))) 
      from (select property as propertyid from eg_pt_propertydetail_v2
      $where and
        additionaldetails is not null and additionaldetails !='null'
      ) vasika_results
    groupBy:    
    orderBy: 
   searchParams:
    condition: AND
    params:
    - name: tenantid
      isMandatory: false
      jsonPath: $.searchCriteria.tenantId
    - name: additionaldetails->>'vasikano'
      isMandatory: true
      jsonPath: $.searchCriteria.vasikano

   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.services
    responseInfoPath: $.ResponseInfo