SearchDefinitions:
 moduleName: rainmaker-pt-gissearch
 summary: Searcher configuration for Adhoc Requirment
 version: 1.0.0
 definitions:

 - name: searchNewTaxPayments
   query:
    baseQuery: |
      select array_to_json(array_agg(row_to_json(data))) from (
        select
          pt.propertyid as propertyid,
          pt.oldpropertyid as oldpropertyid,
          pd.receiptnumber as receiptnumber,
          pt.tenantid as tenantid,
          pd.receiptdate::varchar as receiptdate
        from
        egcl_paymentdetail AS pd
        INNER JOIN egcl_bill on pd.billid=egcl_bill.id
        INNER JOIN eg_pt_property AS pt ON pt.propertyid = egcl_bill.consumercode
        AND pt.oldpropertyid IS NOT NULL
        AND
        pt.oldpropertyid != '' $where) data
    groupBy:
    orderBy:
   searchParams:
    condition: AND
    params:
    - name: receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.fromDate
      operator: GE
    - name: receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.toDate
      operator: LE
    - name: pt.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
      operator: =


   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.data
    responseInfoPath: $.ResponseInfo
